amcl:
  ros__parameters:
    use_sim_time: true

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    laser_frame_id: "laser"

    min_particles: 500
    max_particles: 2000

    update_min_d: 0.25
    update_min_a: 0.2

    kld_err: 0.05
    kld_z: 0.99

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.3
    alpha4: 0.3
    alpha5: 0.2

    laser_max_range: 12.0
    laser_min_range: 0.10

    transform_tolerance: 0.5

    autostart: true
