## ekf config file ###
ekf_filter_node:
  ros__parameters:

    frequency: 20.0   
    two_d_mode: true    

    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odometry/data
    odom0_config: [
      false, false, false,     # x, y, z
      false, false, false,     # roll, pitch, yaw
      true,  true, false,     # ẋ, ẏ, ż
      false, false, false,      # roll̇, pitcḣ, yaẇ
      false, false, false      # x¨, y¨, z¨
    ]

    imu0: imu/data
    imu0_config: [
      false, false, false,     # x_pos, y_pos, z_pos
      false, false, true,      # roll, pitch, yaw  <-- dùng orientation từ IMU
      false, false, false,     # linear velocity
      false, false, true,      # roll̇ pitcḣ yaẇ  <-- yaw_rate từ IMU
      false,  false, false      # accel_x fused, accel_y NO, accel_z NO
    ]
